### ISSUE TITLE
[Support request:] Raspberry Pi 5 build based on the upcoming OpenWrt builds for it?

### ISSUE THREAD

**Issue by Daasin** [ofmodemsandmen/RooterSource#11]
Lots of advantages for Pi 5 with the changes to USB and dedicated hats for networking, can even add both a WiFi card alongside additional 2.5Gbe port using the pcie 3 connection too! It's got support for OpenWrt in their dev builds that I've tested although Luci has to be added to them.

Requesting automated nightly builds that pull from OpenWrt and attempts to add Luci with rooter project patches on top. Would be very useful to people who build DIY networking projects. 🙏🏽

**Comment by Daasin** [comment]
Thanks in advance for any consideration to Rpi 5 testing

**Comment by carp4** [comment]
This exists already

http://www.aturnofthenut.com/autobuilds/

The build system is here 

https://github.com/ofmodemsandmen/SourceRPI5

**Comment by Daasin** [comment]
> This exists already
> 
> http://www.aturnofthenut.com/autobuilds/
> 
> The build system is here
> 
> https://github.com/ofmodemsandmen/SourceRPI5

Thank you, my apologies for not noticing it. I'll get onto testing rn! @carp4

**Comment by Daasin** [comment]
Closing request as route for support has already been established 👍🏽

**Comment by carp4** [comment]
Good luck! Please report any issues or comments here

https://forums.whirlpool.net.au/thread/3vx1k1r3?p=-1#bottom
